image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

environment:
  PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%/python -m venv venv"
  - "venv/Scripts/activate.bat"
  - "%PYTHON%/python -m pip install codecov"

test_script:
  - "%PYTHON%/python setup.py test"
  - "codecov"
