language: python
os: linux
dist: xenial
addons:
  apt:
    packages:
      - ca-certificates
      - libc++-dev
      - libiomp-dev
      - g++-6
      - g++-7
      - g++-8
      - g++-9
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'

python:
  - "3.6"
  - "3.7"
env:
  - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"
  - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
  - MATRIX_EVAL="export CC=gcc-9 && export CXX=g++-9"
          
before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip3 install setuptools
  - pip3 install codecov
  - pip3 install pytest
  - python3 setup.py develop

script:
  - python3 -m coverage run setup.py test

after_success:
  - codecov

deploy:
  provider: pypi
  skip_cleanup: true
  skip_existing: true
  user:
    secure: "VFu/N8o1KDXaRMIZmRNeWsR55dWCkghTD1HNscufXETrfz43jJUWDvC0jpwDrns0Csyb2XRHh9jG13w7KFqTXoZCroPBu8eVAeMFLsRJ0pmU7AJqpGvWBGoVNIyrj3NJ8nP1LZGvrOtEPnCVLm3sNWEZtGYSyWhJTUbVcIlvjLY2xwFnsZJkc5d7O/jkKGZ4wbW3DwRTC9z1Ywu2kadEnDdqE38KqwDu0KwrmaKF5odPrkRjnG/AONveNTv+akMYLE4RT8tmmpe4B+lAu/lnihk64Zemc0e1oQZy/MCqZ/G7QPyGQGLGHxK1f21RFIsSY8igoDzYmRT5t3p9NA7wAsbmomrBPQ/TK43eqPEJD9ZiNWs2+pDN5Hew8vTgUAjwRY/BuMQouVYFRq0py3gNspEf+ar2ojOMtRfKeZyl0KrIvZZmrdvEU1cOZDxDYmKu2e9ijgmMc2lfe0nSQHYP9xxj32o7DitN04Ls7/Lm/NFAUMCnerEqCVLzTnoaLPcg0roVt3GmuQ0W+dfJ7pByy7wkBRS1tuFdpvZu8TSWPH/M3kGpRt5/7wP3JbX1aMl6uz7GYOx9wCoblpXODxkPE2JbiSUmAIb2heYeVRVAKPoJkk7lNVNFcYcq7N3Rj3/nBf+eGZXx1/R87sgOsCjoLYHocQs3viOR2cQ8tfpp0q8="
  password:
    secure: "IAbTCe5DQjGGCp4t36FE+QNd0kqGqK6OvO1lkj3I0JKTWl8vhEYvBlxarsRu9DPrQsCndczomrr66gbUo5UQtjtpUso+j1385gBvU2NPEa3HjmL4FUIXQ4uzx9q40GsWg8Znf1qJBg6+Vxc2zGadC5KnXmCSXz1lXLLns5K0T9GrLh4jdYUfVZ/ZLjca6VQd7L3ZmFrCtDXxQzF3tPpVZ+gMTn9TZU2qGXimKAoaQhLOALofGbjRiiAARdFxtN0v68+ryOzyri7glrxsiql04V8A20GARX6FijINCTtkv1svVh/Wxj7nZ+ZLq2VGVK1jWhRQCaG6NacQl4nAn1EtdcBj+jBKasah01sa8JxYheCKMsf7qmfYJpoKABEuHnGpY5HU/Htn8heJ4vwP4xE8d1J+h/gAqGagzYhJYbYElDc5cN8b0G0A8NHful77s9ZLrtwcKh+QThxO4OXkC4L692Bi7puI0NMSGWHCDs6FZ6yFwtxRaKF4nnciT1ikjRCYd6zuiRvGWOvl9aa+p6gBTTFlA+pWsLYIBdEnosKb0EWohe2o28gLw3QTbpaxTjgzivCFugtK1tkv3Gg+mMwwxZhhPYSQm4UCMKODULz235Ras7Ci5nBU5MBzMwZrsFx6eNYDpufaCufVY1WQitgTxSXiHEseXXCcgld4WHul5R8="
  on:
    branch: master
    tags: true
