language: python

matrix:
  include:
    - language: python
      os: linux
      python: 3.7
      addons:
        apt:
          packages:
            - ca-certificates
            - libc++-dev
            - g++-8
            - libiomp-dev
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
      dist: xenial

install:
  - export CC=gcc-8
  - export CXX=g++-8
  - pip3 install setuptools
  - pip3 install codecov
  - pip3 install pytest
  - python3 setup.py develop

script:
  - python3 -m coverage run setup.py test

after_sucess:
  - codecov
