name: Test Python 🐍 package 📦 on Windows ⊞
on: [push]
jobs:
  Build-and-Test:
    name: Build and test on Windows using Python ${{ matrix.python-version }} / gcc ${{ matrix.gcc-version }}
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools codecov pytest
          pip install -e .

      - name: Run tests and create coverage report
        run : |
          coverage run -m pytest tests -v

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
